# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odttemplate',
            name='file_name',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
