# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_documents', '0003_auto_20160712_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='odttemplate',
            name='generated_file_name',
            field=models.CharField(default='default', help_text='El nombre final que va a tener el documento cuando se env\xede por correo o se suba a PODIO. Admite sintaxis de templates de Django para valores din\xe1micos', max_length=32, verbose_name='Nombre autogenerado'),
        ),
        migrations.AlterField(
            model_name='odttemplate',
            name='file_name',
            field=models.SlugField(default='default', help_text='El nombre que va a tener el archivo cuando se guarde', max_length=32),
        ),
        migrations.AlterField(
            model_name='odttemplate',
            name='name',
            field=models.CharField(db_index=True, help_text='Un nombre \xfanico para este documento que sirva para identificarlo y diferenciarlo de los dem\xe1s', max_length=16, unique=True, verbose_name='Nombre'),
        ),
    ]
