# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_documents', '0004_auto_20160816_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odttemplate',
            name='name',
            field=models.CharField(db_index=True, help_text='Un nombre \xfanico para este documento que sirva para identificarlo y diferenciarlo de los dem\xe1s', max_length=32, unique=True, verbose_name='Nombre'),
        ),
    ]
